name: CI Build

on:
	push:
		branches: [ master ]
	pull_request:
		branches: [ master ]

jobs:
	build-android:
		name: Build Android APK
		runs-on: ubuntu-latest
		steps:
			- uses: actions/checkout@v4
			- name: Set up JDK 17
				uses: actions/setup-java@v4
				with:
					distribution: 'temurin'
					java-version: '17'
			- name: Grant execute permission for gradlew
				run: chmod +x ./Android/gradlew
			- name: Build Debug APK
				run: ./Android/gradlew -p Android assembleDebug
			- name: Upload APK artifact
				uses: actions/upload-artifact@v4
				with:
					name: android-apk
					path: Android/app/build/outputs/apk/debug/*.apk

	build-windows:
		name: Build Windows Native
		runs-on: windows-latest
		steps:
			- uses: actions/checkout@v4
			- name: Set up MSVC
				uses: ilammy/msvc-dev-cmd@v1
			- name: Configure CMake
				run: cmake -S . -B build -A x64
			- name: Build
				run: cmake --build build --config Release
			- name: Upload Windows binaries
				uses: actions/upload-artifact@v4
				with:
					name: windows-binaries
					path: build/Release/

	build-macos:
		name: Build macOS Native
		runs-on: macos-latest
		steps:
			- uses: actions/checkout@v4
			- name: Configure CMake
				run: cmake -S . -B build
			- name: Build
				run: cmake --build build --config Release
			- name: Upload macOS binaries
				uses: actions/upload-artifact@v4
				with:
					name: macos-binaries
					path: build/Release/
